### ISSUE TITLE
Fix ảnh - sai đề

### ISSUE THREAD

**Issue by WyvernPJ** [trietptm/De-Thi-Toan-Chuyen-Tuyen-Sinh-Lop-10-Chuyen-Toan-PTNK#2]
![image](https://github.com/trietptm/De-Thi-Toan-Chuyen-Tuyen-Sinh-Lop-10-Chuyen-Toan-PTNK/assets/99076505/818dcd17-f6d4-4060-adfc-94bf8a17179f)
đề thì kêu 10 đội bóng nhưng giải lại là giải của 4 đội bóng

**Comment by trietptm** [comment]
Đây là một bài toán trong một bài viết chuyên đề riêng được giới thiệu trên trang của nhà trường, mình sẽ cập nhật nếu bài viết trên được cập nhật.
